<script setup lang="ts">
import websiteV1Img from '@/assets/website-v1.webp'
import websiteV2Img from '@/assets/website-v2.webp'
import websiteV3Img from '@/assets/website-v3.webp'

const versions: {
  version: number
  name: string
  img: string
  release: string
  fun_fact: string
  link: string
  src: string
  sep: boolean
}[] = [
    {
      version: 1,
      name: 'Initial',
      img: websiteV1Img,
      release: 'Oct 18, 2023',
      fun_fact:
        "This entire website was generated by ChatGPT, I only provided the content. Why? Well, I had just learned HTML, and instead of practicing my new learnt skill, my stupid self immediately decided I was ready to work at Google, and didn't need to waste my time focusing on silly things like building a website.",
      link: '/v1/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v1',
      sep: true
    },
    {
      version: 2,
      name: 'Gradient update',
      img: websiteV2Img,
      release: 'Mar 7, 2025',
      fun_fact:
        'After making a graded demo website for my school, I realized the design of my portfolio was actually ass, which made me want to seriously work on it.',
      link: '/v2/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v2',
      sep: true
    },
    {
      version: 3,
      name: 'The New York Times update',
      img: websiteV3Img,
      release: 'Mar 11, 2025',
      fun_fact:
        'This version came to life because of the background animation of the previous one, it was too complicated to make it responsive across different screen sizes so I decided to ditched it.',
      link: '/v3/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v3',
      sep: false
    },
  ]
</script>

<template>
  <div class="py-4">
    <div class="px-12 py-6 flex flex-col sm:flex-row gap-3 items-center" v-for="version in versions" :key="version.version"
      :class="version.sep ? 'border-b' : ''">
      <div class="mb-4 w-full sm:mb-0 sm:w-64 shrink-0">
        <img :src="version.img" :alt="`Version ${version.version}`"
          class="w-full aspect-video object-cover rounded-lg" />
      </div>
      <div class="w-full">
        <h3 class="text-lg font-semibold">v{{ version.version }} - {{ version.name }}</h3>
        <p class="text-sm text-gray-500">{{ version.release }}</p>
        <p class="mt-2">{{ version.fun_fact }}</p>
        <div class="py-3 gap-2 flex">
          <a class="border py-2 px-3 rounded-full" :href="version.link">See live</a>
          <a class="border py-2 px-3 rounded-full" :href="version.src">View source</a>
        </div>
      </div>
    </div>
  </div>
</template>
