<script setup lang="ts">
import websiteV1Img from '@/assets/website-v1.webp'
import websiteV2Img from '@/assets/website-v2.webp'
import websiteV3Img from '@/assets/website-v3.webp'
import websiteV4Img from '@/assets/website-v4.webp'

const versions: {
  version: number
  name: string
  img: string
  release: string
  fun_fact: string
  link: string
  src: string
  sep: boolean
}[] = [
    {
      version: 1,
      name: 'Initial',
      img: websiteV1Img,
      release: 'Oct 18, 2023',
      fun_fact:
        "This entire website was generated by ChatGPT, I only provided the content. Why? Well, I had just learned HTML, and instead of practicing my new learnt skill, my stupid self immediately decided I was ready to work at Google, and didn't need to waste my time focusing on silly things like building a website.",
      link: '/v1/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v1',
      sep: true,
    },
    {
      version: 2,
      name: 'Gradient update',
      img: websiteV2Img,
      release: 'Mar 7, 2025',
      fun_fact:
        'After making a graded demo website for my school, I realized the design of my portfolio was actually ass, which made me want to seriously work on it.',
      link: '/v2/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v2',
      sep: true,
    },
    {
      version: 3,
      name: 'The New York Times update',
      img: websiteV3Img,
      release: 'Mar 11, 2025',
      fun_fact:
        'This version came to life because of the background animation of the previous one, it was too complicated to make it responsive across different screen sizes so I decided to ditched it.',
      link: '/v3/',
      src: 'https://github.com/Saterz/saterz.dev/tree/v3',
      sep: true,
    },
    {
      version: 4,
      name: 'Incoming...',
      img: websiteV4Img,
      release: 'Xyz 00, 0000',
      fun_fact: 'A complete rewrite in Vue. Coming soon...',
      link: '/',
      src: 'https://github.com/Saterz/saterz.dev/tree/main',
      sep: false,
    },
  ]
</script>

<template>
  <div class="versions">
    <div class="version" v-for="version in versions" :key="version.version" :class="{ separator: version.sep }">
      <div class="version-thumbnail">
        <img :src="version.img" />
      </div>
      <div class="version-content">
        <h3>v{{ version.version }} - {{ version.name }}</h3>
        <p class="release">{{ version.release }}</p>
        <p class="fun-fact">{{ version.fun_fact }}</p>
        <div class="links">
          <a :href="version.link">See live</a>
          <a :href="version.src">View source</a>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.versions {
  padding-block: 1rem;
}

.version {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.75rem;
  padding-inline: 3rem;
  padding-block: 1.5rem;
}

.separator {
  border-bottom: 1px solid var(--color-border);
}

.version-thumbnail {
  flex-shrink: 0;
  width: 100%;
  margin-bottom: 1rem;
}

.version-thumbnail img {
  display: block;
  width: 100%;
  aspect-ratio: 16 / 9;
  object-fit: cover;
  border-radius: 0.5rem;
}

.version-content {
  width: 100%;
}

h3 {
  font-size: 1.125rem;
  font-weight: 600;
}

.release {
  color: #6b7280;
  font-size: 0.875rem;
}

.fun-fact {
  margin-top: 0.5rem;
}

.links {
  display: flex;
  gap: 0.5rem;
  padding-block: 0.75rem;
}

.links a {
  padding: 0.5rem 0.75rem;
  border: 1px solid var(--color-border);
  border-radius: 9999px;
}

@media (min-width: 640px) {
  .version {
    flex-direction: row;
  }

  .version-thumbnail {
    width: 16rem;
    margin-bottom: 0;
  }
}
</style>
